/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iterum.viewer;

import iterum.controller.GerenciadorInterfaceGrafica;
import iterum.viewer.componentes.PnlLinkBarraLateral;
import javax.swing.JPanel;

import iterum.controller.Tela;

/**
 *
 * @author evandro
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public FrmPrincipal() {
        initComponents();

        this.setLocationRelativeTo(null);

        for (Tela tela : Tela.values()) {
            if (!tela.getLabel().equals("")) {
                pnlBarraLateral.add(new PnlLinkBarraLateral(tela));

            }
        }
    }

    public JPanel getPnlConteudo() {
        return pnlConteudo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlConteudo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITERUM");
        setMinimumSize(new java.awt.Dimension(1000, 800));

        pnlBarraLateral.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        pnlBarraLateral.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));
        pnlBarraLateral.setMinimumSize(new java.awt.Dimension(200, 0));
        pnlBarraLateral.setPreferredSize(new java.awt.Dimension(200, 0));
        pnlBarraLateral.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        jLabel1.setFont(new java.awt.Font("Liberation Mono", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITERUM");
        pnlBarraLateral.add(jLabel1);

        getContentPane().add(pnlBarraLateral, java.awt.BorderLayout.WEST);

        pnlConteudo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConteudo.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // 1. Registra o pacote "iterum" como fonte de customizações
            com.formdev.flatlaf.FlatLaf.registerCustomDefaultsSource("iterum");

            // 2. Inicializa o tema Light (ele buscará o arquivo FlatLightLaf.properties)
            com.formdev.flatlaf.FlatLightLaf.setup();

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Erro ao carregar o tema IFES", ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            FrmPrincipal frame = new FrmPrincipal();
            GerenciadorInterfaceGrafica.instancia.definirMainFrame(frame);
            frame.setVisible(true);
            GerenciadorInterfaceGrafica.instancia.abrirTela(Tela.DASHBOARD);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBarraLateral;
    private javax.swing.JPanel pnlConteudo;
    // End of variables declaration//GEN-END:variables
}
