/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.viewer;

import iterum.controller.GerenciadorInterfaceGrafica;
import iterum.domain.EtapaProjeto;
import iterum.domain.Projeto;
import iterum.domain.Tarefa;
import java.awt.Color;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author evandro
 */
public class PnlProjeto extends javax.swing.JPanel {

    /**
     * Creates new form PnlProjeto
     */
    public PnlProjeto() {
        initComponents();
        atualizarQuadro();
    }

    public final void atualizarQuadro() {
        Projeto projeto = GerenciadorInterfaceGrafica.instancia.getProjetoSelecionado();
        lblNomeProjeto.setText(projeto == null ? "Selecione um projeto" : projeto.getNome());

        List<EtapaProjeto> etapas = GerenciadorInterfaceGrafica.instancia.listarEtapasProjetoSelecionado();
        popularColuna(etapas, 0, lblTituloBacklog, pnlListaBacklog);
        popularColuna(etapas, 1, lblTituloAndamento, pnlListaAndamento);
        popularColuna(etapas, 2, lblTituloRevisao, pnlListaRevisao);
        popularColuna(etapas, 3, lblTituloConcluido, pnlListaConcluido);
    }

    private void popularColuna(List<EtapaProjeto> etapas, int indice, JLabel lblEtapa, JPanel pnlLista) {
        pnlLista.removeAll();

        if (indice >= etapas.size()) {
            lblEtapa.setText("ETAPA");
            pnlLista.revalidate();
            pnlLista.repaint();
            return;
        }

        EtapaProjeto etapa = etapas.get(indice);
        lblEtapa.setText(etapa.getNome());

        for (Tarefa tarefa : etapa.getTarefas()) {
            pnlLista.add(criarCardTarefa(tarefa));
        }

        pnlLista.revalidate();
        pnlLista.repaint();
    }

    private JPanel criarCardTarefa(Tarefa tarefa) {
        JPanel card = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 8));
        card.setOpaque(true);
        card.setBackground(Color.WHITE);
        card.setBorder(
                BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));

        JLabel lblNome = new JLabel(tarefa.getNome());
        card.add(lblNome);
        return card;
    }

    private EtapaProjeto getEtapaPorIndice(int indice) {
        List<EtapaProjeto> etapas = GerenciadorInterfaceGrafica.instancia.listarEtapasProjetoSelecionado();
        if (indice < 0 || indice >= etapas.size()) {
            return null;
        }
        return etapas.get(indice);
    }

    private void abrirDialogAdicionarTarefa(EtapaProjeto etapa) {
        if (etapa == null) {
            return;
        }

        GerenciadorInterfaceGrafica.instancia.solicitarNovaTarefa(this, etapa.getNome())
                .ifPresent(nomeTarefa -> {
                    GerenciadorInterfaceGrafica.instancia.adicionarTarefaNaEtapa(etapa, nomeTarefa);
                    atualizarQuadro();
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopo = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNomeProjeto = new javax.swing.JLabel();
        jScrollPaneQuadro = new javax.swing.JScrollPane();
        pnlQuadro = new javax.swing.JPanel();
        pnlColunaBacklog = new javax.swing.JPanel();
        pnlHeaderBacklog = new javax.swing.JPanel();
        lblTituloBacklog = new javax.swing.JLabel();
        btnAdicionarBacklog = new javax.swing.JButton();
        jScrollPaneBacklog = new javax.swing.JScrollPane();
        pnlListaBacklog = new javax.swing.JPanel();
        pnlColunaAndamento = new javax.swing.JPanel();
        pnlHeaderAndamento = new javax.swing.JPanel();
        lblTituloAndamento = new javax.swing.JLabel();
        btnAdicionarAndamento = new javax.swing.JButton();
        jScrollPaneAndamento = new javax.swing.JScrollPane();
        pnlListaAndamento = new javax.swing.JPanel();
        pnlColunaRevisao = new javax.swing.JPanel();
        pnlHeaderRevisao = new javax.swing.JPanel();
        lblTituloRevisao = new javax.swing.JLabel();
        btnAdicionarRevisao = new javax.swing.JButton();
        jScrollPaneRevisao = new javax.swing.JScrollPane();
        pnlListaRevisao = new javax.swing.JPanel();
        pnlColunaConcluido = new javax.swing.JPanel();
        pnlHeaderConcluido = new javax.swing.JPanel();
        lblTituloConcluido = new javax.swing.JLabel();
        btnAdicionarConcluido = new javax.swing.JButton();
        jScrollPaneConcluido = new javax.swing.JScrollPane();
        pnlListaConcluido = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlCabecalho.setLayout(new javax.swing.BoxLayout(pnlCabecalho, javax.swing.BoxLayout.Y_AXIS));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 42)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PROJETO");
        lblTitulo.setAlignmentX(0.5F);
        pnlCabecalho.add(lblTitulo);

        lblNomeProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeProjeto.setText("-");
        lblNomeProjeto.setAlignmentX(0.5F);
        pnlCabecalho.add(lblNomeProjeto);

        pnlTopo.add(pnlCabecalho);

        add(pnlTopo, java.awt.BorderLayout.NORTH);

        jScrollPaneQuadro.setBorder(null);

        pnlQuadro.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        pnlQuadro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        pnlColunaBacklog.setBorder(javax.swing.BorderFactory
                .createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));
        pnlColunaBacklog.setPreferredSize(new java.awt.Dimension(240, 460));
        pnlColunaBacklog.setLayout(new java.awt.BorderLayout());

        pnlHeaderBacklog.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlHeaderBacklog.setLayout(new java.awt.BorderLayout(8, 0));

        lblTituloBacklog.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTituloBacklog.setText("BACKLOG");
        pnlHeaderBacklog.add(lblTituloBacklog);

        btnAdicionarBacklog.setText("+ Tarefa");
        btnAdicionarBacklog.addActionListener(this::btnAdicionarBacklogActionPerformed);
        pnlHeaderBacklog.add(btnAdicionarBacklog, java.awt.BorderLayout.EAST);

        pnlColunaBacklog.add(pnlHeaderBacklog, java.awt.BorderLayout.NORTH);

        jScrollPaneBacklog.setBorder(null);

        pnlListaBacklog.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        pnlListaBacklog.setLayout(new javax.swing.BoxLayout(pnlListaBacklog, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneBacklog.setViewportView(pnlListaBacklog);

        pnlColunaBacklog.add(jScrollPaneBacklog, java.awt.BorderLayout.CENTER);

        pnlQuadro.add(pnlColunaBacklog);

        pnlColunaAndamento.setBorder(javax.swing.BorderFactory
                .createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));
        pnlColunaAndamento.setPreferredSize(new java.awt.Dimension(240, 460));
        pnlColunaAndamento.setLayout(new java.awt.BorderLayout());

        pnlHeaderAndamento.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlHeaderAndamento.setLayout(new java.awt.BorderLayout(8, 0));

        lblTituloAndamento.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTituloAndamento.setText("EM ANDAMENTO");
        pnlHeaderAndamento.add(lblTituloAndamento);

        btnAdicionarAndamento.setText("+ Tarefa");
        btnAdicionarAndamento.addActionListener(this::btnAdicionarAndamentoActionPerformed);
        pnlHeaderAndamento.add(btnAdicionarAndamento, java.awt.BorderLayout.EAST);

        pnlColunaAndamento.add(pnlHeaderAndamento, java.awt.BorderLayout.NORTH);

        jScrollPaneAndamento.setBorder(null);

        pnlListaAndamento.setLayout(new javax.swing.BoxLayout(pnlListaAndamento, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneAndamento.setViewportView(pnlListaAndamento);

        pnlColunaAndamento.add(jScrollPaneAndamento, java.awt.BorderLayout.CENTER);

        pnlQuadro.add(pnlColunaAndamento);

        pnlColunaRevisao.setBorder(javax.swing.BorderFactory
                .createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));
        pnlColunaRevisao.setPreferredSize(new java.awt.Dimension(240, 460));
        pnlColunaRevisao.setLayout(new java.awt.BorderLayout());

        pnlHeaderRevisao.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlHeaderRevisao.setLayout(new java.awt.BorderLayout(8, 0));

        lblTituloRevisao.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTituloRevisao.setText("REVISAO");
        pnlHeaderRevisao.add(lblTituloRevisao);

        btnAdicionarRevisao.setText("+ Tarefa");
        btnAdicionarRevisao.addActionListener(this::btnAdicionarRevisaoActionPerformed);
        pnlHeaderRevisao.add(btnAdicionarRevisao, java.awt.BorderLayout.EAST);

        pnlColunaRevisao.add(pnlHeaderRevisao, java.awt.BorderLayout.NORTH);

        jScrollPaneRevisao.setBorder(null);

        pnlListaRevisao.setLayout(new javax.swing.BoxLayout(pnlListaRevisao, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneRevisao.setViewportView(pnlListaRevisao);

        pnlColunaRevisao.add(jScrollPaneRevisao, java.awt.BorderLayout.CENTER);

        pnlQuadro.add(pnlColunaRevisao);

        pnlColunaConcluido.setBorder(javax.swing.BorderFactory
                .createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));
        pnlColunaConcluido.setPreferredSize(new java.awt.Dimension(240, 460));
        pnlColunaConcluido.setLayout(new java.awt.BorderLayout());

        pnlHeaderConcluido.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlHeaderConcluido.setLayout(new java.awt.BorderLayout(8, 0));

        lblTituloConcluido.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTituloConcluido.setText("CONCLUIDO");
        pnlHeaderConcluido.add(lblTituloConcluido);

        btnAdicionarConcluido.setText("+ Tarefa");
        btnAdicionarConcluido.addActionListener(this::btnAdicionarConcluidoActionPerformed);
        pnlHeaderConcluido.add(btnAdicionarConcluido, java.awt.BorderLayout.EAST);

        pnlColunaConcluido.add(pnlHeaderConcluido, java.awt.BorderLayout.NORTH);

        jScrollPaneConcluido.setBorder(null);

        pnlListaConcluido.setLayout(new javax.swing.BoxLayout(pnlListaConcluido, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneConcluido.setViewportView(pnlListaConcluido);

        pnlColunaConcluido.add(jScrollPaneConcluido, java.awt.BorderLayout.CENTER);

        pnlQuadro.add(pnlColunaConcluido);

        jScrollPaneQuadro.setViewportView(pnlQuadro);

        add(jScrollPaneQuadro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarBacklogActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarBacklogActionPerformed
        abrirDialogAdicionarTarefa(getEtapaPorIndice(0));
    }// GEN-LAST:event_btnAdicionarBacklogActionPerformed

    private void btnAdicionarAndamentoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarAndamentoActionPerformed
        abrirDialogAdicionarTarefa(getEtapaPorIndice(1));
    }// GEN-LAST:event_btnAdicionarAndamentoActionPerformed

    private void btnAdicionarRevisaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarRevisaoActionPerformed
        abrirDialogAdicionarTarefa(getEtapaPorIndice(2));
    }// GEN-LAST:event_btnAdicionarRevisaoActionPerformed

    private void btnAdicionarConcluidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarConcluidoActionPerformed
        abrirDialogAdicionarTarefa(getEtapaPorIndice(3));
    }// GEN-LAST:event_btnAdicionarConcluidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAndamento;
    private javax.swing.JButton btnAdicionarBacklog;
    private javax.swing.JButton btnAdicionarConcluido;
    private javax.swing.JButton btnAdicionarRevisao;
    private javax.swing.JScrollPane jScrollPaneAndamento;
    private javax.swing.JScrollPane jScrollPaneBacklog;
    private javax.swing.JScrollPane jScrollPaneConcluido;
    private javax.swing.JScrollPane jScrollPaneQuadro;
    private javax.swing.JScrollPane jScrollPaneRevisao;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloAndamento;
    private javax.swing.JLabel lblTituloBacklog;
    private javax.swing.JLabel lblTituloConcluido;
    private javax.swing.JLabel lblTituloRevisao;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlColunaAndamento;
    private javax.swing.JPanel pnlColunaBacklog;
    private javax.swing.JPanel pnlColunaConcluido;
    private javax.swing.JPanel pnlColunaRevisao;
    private javax.swing.JPanel pnlHeaderAndamento;
    private javax.swing.JPanel pnlHeaderBacklog;
    private javax.swing.JPanel pnlHeaderConcluido;
    private javax.swing.JPanel pnlHeaderRevisao;
    private javax.swing.JPanel pnlListaAndamento;
    private javax.swing.JPanel pnlListaBacklog;
    private javax.swing.JPanel pnlListaConcluido;
    private javax.swing.JPanel pnlListaRevisao;
    private javax.swing.JPanel pnlQuadro;
    private javax.swing.JPanel pnlTopo;
    // End of variables declaration//GEN-END:variables
}
