/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.viewer;

import iterum.viewer.componentes.PnlCardProjeto;

/**
 *
 * @author evandro
 */
public class PnlProjetos extends javax.swing.JPanel {

    /**
     * Creates new form pnlProjetos
     */
    public PnlProjetos() {
        initComponents();
        
        atualizarListagem();
    }

    public void atualizarListagem() {
        pnlListaProjetos.removeAll();
        
        for (int i = 0; i < 7; i++) {
            pnlListaProjetos.add(new PnlCardProjeto());
        }

        pnlListaProjetos.revalidate();
        pnlListaProjetos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopo = new javax.swing.JPanel();
        pnlEsquerda = new javax.swing.JPanel();
        pnlCentro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlDireita = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        pnlListaProjetos = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlTopo.setLayout(new java.awt.GridLayout(1, 3));

        pnlEsquerda.setLayout(new java.awt.BorderLayout());
        pnlTopo.add(pnlEsquerda);

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PROJETOS");
        pnlCentro.add(lblTitulo);

        pnlTopo.add(pnlCentro);

        pnlDireita.setLayout(new java.awt.BorderLayout());

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDireita.add(btnAdicionar, java.awt.BorderLayout.LINE_END);

        pnlTopo.add(pnlDireita);

        add(pnlTopo, java.awt.BorderLayout.NORTH);

        pnlListaProjetos.setLayout(new java.awt.FlowLayout(1, 10, 10));
        add(pnlListaProjetos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlDireita;
    private javax.swing.JPanel pnlEsquerda;
    private javax.swing.JPanel pnlListaProjetos;
    private javax.swing.JPanel pnlTopo;
    // End of variables declaration//GEN-END:variables
}
