/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.view.componentes;

/**
 *
 * @author evandro
 */
public class PnlLinkBarraLateral extends javax.swing.JPanel {

    /**
     * Creates new form PnlLinkBarraLateral
     */
    public PnlLinkBarraLateral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLink = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setMaximumSize(new java.awt.Dimension(180, 50));
        setMinimumSize(new java.awt.Dimension(180, 50));
        setPreferredSize(new java.awt.Dimension(180, 50));
        setLayout(new java.awt.BorderLayout());

        btnLink.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        btnLink.setText("LINK");
        add(btnLink, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLink;
    // End of variables declaration//GEN-END:variables
}
