/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.view.componentes;

/**
 *
 * @author evandro
 */
public class PnlLinkBarraLateral extends javax.swing.JPanel {

    /**
     * Creates new form PnlLinkBarraLateral
     */
    public PnlLinkBarraLateral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLink = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(180, 50));
        setMinimumSize(new java.awt.Dimension(180, 50));
        setPreferredSize(new java.awt.Dimension(180, 50));
        setLayout(new java.awt.BorderLayout());

        lblLink.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        lblLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLink.setText("LINK");
        lblLink.setMaximumSize(new java.awt.Dimension(180, 50));
        lblLink.setMinimumSize(new java.awt.Dimension(180, 50));
        lblLink.setPreferredSize(new java.awt.Dimension(180, 50));
        add(lblLink, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLink;
    // End of variables declaration//GEN-END:variables
}
