/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.viewer.componentes;

/**
 *
 * @author evandro
 */
public class PnlCardDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PnlCardDashboard
     */
    public PnlCardDashboard(String titulo, String valor) {
        initComponents();
        
        lblTitulo.setText(titulo);
        lblValor.setText(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"), 2, true));
        setPreferredSize(new java.awt.Dimension(180, 80));
        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("TITULO");
        lblTitulo.setMaximumSize(new java.awt.Dimension(120, 80));
        lblTitulo.setMinimumSize(new java.awt.Dimension(120, 80));
        lblTitulo.setName(""); // NOI18N
        add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        lblValor.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor.setText("VALOR");
        add(lblValor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
