/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.viewer.componentes;

import iterum.controller.GerenciadorInterfaceGrafica;
import iterum.controller.Tela;

/**
 *
 * @author evandro
 */
public class PnlCardProjeto extends javax.swing.JPanel {

    /**
     * Creates new form PnlCardProjeto
     */
    public PnlCardProjeto() {
        initComponents();

        // Criamos um adaptador que repassa os eventos para o painel principal
        java.awt.event.MouseAdapter redirecionador = new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        };

        pbProgresso.addMouseListener(redirecionador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pbProgresso = new javax.swing.JProgressBar();
        pnlDetalhes = new javax.swing.JPanel();
        lblTarefas = new javax.swing.JLabel();
        lblPrazo = new javax.swing.JLabel();
        lblMembros = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"), 2, true));
        setMaximumSize(new java.awt.Dimension(230, 150));
        setMinimumSize(new java.awt.Dimension(230, 150));
        setPreferredSize(new java.awt.Dimension(230, 150));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTitulo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        pnlTitulo.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        pnlTitulo.setLayout(new java.awt.GridLayout(1, 0));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema ERP");
        pnlTitulo.add(lblTitulo);

        add(pnlTitulo);

        pbProgresso.setToolTipText("");
        pbProgresso.setValue(50);
        pbProgresso.setBorder(null);
        pbProgresso.setStringPainted(true);
        add(pbProgresso);

        pnlDetalhes.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        pnlDetalhes.setLayout(new java.awt.GridLayout(3, 0));

        lblTarefas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTarefas.setText(" 24 tarefas • 15 concluídas");
        pnlDetalhes.add(lblTarefas);

        lblPrazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrazo.setText(" Prazo: 12 Julho");
        pnlDetalhes.add(lblPrazo);

        lblMembros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMembros.setText("3 membros");
        pnlDetalhes.add(lblMembros);

        add(pnlDetalhes);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBorder(new com.formdev.flatlaf.ui.FlatLineBorder(
                new java.awt.Insets(2, 2, 2, 2),
                javax.swing.UIManager.getColor("Button.focusedBorderColor"),
                2f,
                15
        ));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBorder(new com.formdev.flatlaf.ui.FlatLineBorder(
                new java.awt.Insets(2, 2, 2, 2),
                javax.swing.UIManager.getColor("Button.borderColor"),
                2f,
                2
        ));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        GerenciadorInterfaceGrafica.instancia.abrirTela(Tela.PROJETO);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMembros;
    private javax.swing.JLabel lblPrazo;
    private javax.swing.JLabel lblTarefas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JProgressBar pbProgresso;
    private javax.swing.JPanel pnlDetalhes;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}