/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.viewer.componentes;

import iterum.controller.GerenciadorInterfaceGrafica;
import iterum.controller.Tela;

/**
 *
 * @author evandro
 */
public class PnlLinkBarraLateral extends javax.swing.JPanel {

    private final Tela tela;
    
    public PnlLinkBarraLateral(Tela tela) {
        initComponents();
        this.tela = tela;
        btnLink.setText(tela.getLabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLink = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setMaximumSize(new java.awt.Dimension(180, 50));
        setMinimumSize(new java.awt.Dimension(180, 50));
        setPreferredSize(new java.awt.Dimension(180, 50));
        setLayout(new java.awt.BorderLayout());

        btnLink.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        btnLink.setText("LINK");
        btnLink.addActionListener(this::btnLinkActionPerformed);
        add(btnLink, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkActionPerformed
        GerenciadorInterfaceGrafica.instancia.abrirTela(tela);
    }//GEN-LAST:event_btnLinkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLink;
    // End of variables declaration//GEN-END:variables
}
