/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iterum.viewer.dialog;

import java.awt.Window;
import javax.swing.JOptionPane;

/**
 *
 * @author evandro
 */
public class DlgContribuidorCadastro extends javax.swing.JDialog {

    private boolean confirmado;

    /**
     * Creates new form DlgContribuidorCadastro
     */
    public DlgContribuidorCadastro(Window parent, boolean modal) {
        super(parent);
        initComponents();
        setModal(modal);
        setLocationRelativeTo(parent);
    }

    public boolean isConfirmado() {
        return confirmado;
    }

    public String getNomeInformado() {
        return txtNome.getText().trim();
    }

    public String getEmailInformado() {
        return txtEmail.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pnlAcoes = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Membro da Equipe");
        setMinimumSize(new java.awt.Dimension(500, 260));

        pnlFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 10, 20));
        pnlFormulario.setLayout(new java.awt.GridLayout(4, 1, 0, 8));

        lblNome.setText("Nome");
        pnlFormulario.add(lblNome);

        pnlFormulario.add(txtNome);

        lblEmail.setText("Email");
        pnlFormulario.add(lblEmail);

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        pnlFormulario.add(txtEmail);

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlAcoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));
        pnlAcoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        pnlAcoes.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        pnlAcoes.add(btnSalvar);

        getContentPane().add(pnlAcoes, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        confirmado = false;
        dispose();
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do colaborador.", "Validacao",
                    JOptionPane.WARNING_MESSAGE);
            txtNome.requestFocusInWindow();
            return;
        }

        if (txtEmail.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "Informe o email do colaborador.", "Validacao",
                    JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocusInWindow();
            return;
        }

        confirmado = true;
        dispose();
    }// GEN-LAST:event_btnSalvarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEmailActionPerformed
        btnSalvar.doClick();
    }// GEN-LAST:event_txtEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
