/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iterum.viewer.dialog;

import iterum.domain.Contribuidor;
import iterum.domain.Tarefa;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Optional;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author evandro
 */
public class DlgTarefaCadastro extends javax.swing.JDialog {

    private boolean confirmado;
    private JList<Contribuidor> lstContribuidores;

    /**
     * Creates new form DlgTarefaCadastro
     */
    public DlgTarefaCadastro(Window parent, boolean modal, String etapa) {
        super(parent);
        initComponents();
        setModal(modal);
        lblEtapaValor.setText(etapa);
        setLocationRelativeTo(parent);
    }

    public DlgTarefaCadastro(Window parent, boolean modal, String etapa, List<Contribuidor> contribuidores) {
        this(parent, modal, etapa, null, contribuidores);
    }

    public DlgTarefaCadastro(Window parent, boolean modal, String etapa, Tarefa tarefa, List<Contribuidor> contribuidores) {
        super(parent);
        initComponents();
        setModal(modal);
        lblEtapaValor.setText(etapa);
        configurarListaContribuidores(contribuidores, tarefa);
        if (tarefa != null) {
            setTitle("Editar Tarefa");
            txtNome.setText(tarefa.getNome());
            txtNome.selectAll();
        }
        setLocationRelativeTo(parent);
    }

    public Optional<String> getNomeTarefa() {
        if (!confirmado) {
            return Optional.empty();
        }
        return Optional.of(txtNome.getText().trim());
    }

    public List<Contribuidor> getContribuidoresSelecionados() {
        if (!confirmado || lstContribuidores == null) {
            return List.of();
        }
        return new ArrayList<>(lstContribuidores.getSelectedValuesList());
    }

    private void configurarListaContribuidores(List<Contribuidor> contribuidores, Tarefa tarefa) {
        JLabel lblContribuidores = new JLabel("Colaboradores");
        DefaultListModel<Contribuidor> model = new DefaultListModel<>();
        if (contribuidores != null) {
            for (Contribuidor contribuidor : contribuidores) {
                model.addElement(contribuidor);
            }
        }

        lstContribuidores = new JList<>(model);
        lstContribuidores.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        if (tarefa != null && tarefa.getContribuidores() != null) {
            Set<Integer> idsSelecionados = tarefa.getContribuidores().stream()
                    .map(Contribuidor::getId)
                    .collect(Collectors.toSet());
            for (int i = 0; i < model.size(); i++) {
                Contribuidor contribuidor = model.getElementAt(i);
                if (idsSelecionados.contains(contribuidor.getId())) {
                    lstContribuidores.addSelectionInterval(i, i);
                }
            }
        }

        JScrollPane scrollPane = new JScrollPane(lstContribuidores);
        scrollPane.setPreferredSize(new java.awt.Dimension(440, 120));

        pnlFormulario.removeAll();
        pnlFormulario.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 8, 0);
        pnlFormulario.add(pnlEtapa, gbc);

        gbc.gridy++;
        gbc.insets = new Insets(0, 0, 4, 0);
        pnlFormulario.add(lblNome, gbc);

        gbc.gridy++;
        gbc.insets = new Insets(0, 0, 10, 0);
        pnlFormulario.add(txtNome, gbc);

        gbc.gridy++;
        gbc.insets = new Insets(0, 0, 4, 0);
        pnlFormulario.add(lblContribuidores, gbc);

        gbc.gridy++;
        gbc.weighty = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 0, 0);
        pnlFormulario.add(scrollPane, gbc);

        setMinimumSize(new java.awt.Dimension(500, 360));
        getContentPane().add(pnlFormulario, BorderLayout.CENTER);
        pnlFormulario.revalidate();
        pnlFormulario.repaint();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        pnlEtapa = new javax.swing.JPanel();
        lblEtapa = new javax.swing.JLabel();
        lblEtapaValor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        pnlAcoes = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Tarefa");
        setMinimumSize(new java.awt.Dimension(500, 240));

        pnlFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 10, 20));
        pnlFormulario.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        pnlEtapa.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lblEtapa.setText("Etapa: ");
        pnlEtapa.add(lblEtapa);

        lblEtapaValor.setText("-");
        pnlEtapa.add(lblEtapaValor);

        pnlFormulario.add(pnlEtapa);

        lblNome.setText("Nome da tarefa");
        pnlFormulario.add(lblNome);

        txtNome.addActionListener(this::txtNomeActionPerformed);
        pnlFormulario.add(txtNome);

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlAcoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));
        pnlAcoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        pnlAcoes.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);
        pnlAcoes.add(btnSalvar);

        getContentPane().add(pnlAcoes, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        confirmado = false;
        dispose();
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "Informe o nome da tarefa.", "Validacao", JOptionPane.WARNING_MESSAGE);
            txtNome.requestFocusInWindow();
            return;
        }

        confirmado = true;
        dispose();
    }// GEN-LAST:event_btnSalvarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNomeActionPerformed
        btnSalvar.doClick();
    }// GEN-LAST:event_txtNomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblEtapa;
    private javax.swing.JLabel lblEtapaValor;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JPanel pnlEtapa;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
