/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iterum.view;

import iterum.view.componentes.PnlLinkBarraLateral;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author evandro
 */
public class MainFrame extends javax.swing.JFrame {

    private enum Tela {
        DASHBOARD("dashboard", () -> new PnlDashboard()),
        PROJETOS("projetos", () -> new PnlProjetos()),
        EQUIPE("equipe", () -> new PnlEquipe()),
        RELATORIOS("relatorios", () -> new PnlRelatorios());

        private final String nome;
        private final java.util.function.Supplier<JPanel> lambdaPanel;

        private Tela(String nome, java.util.function.Supplier<JPanel> lambdaPanel) {
            this.nome = nome;
            this.lambdaPanel = lambdaPanel;
        }

        public JPanel getPanel() {
            return lambdaPanel.get();
        }

        public String getNome() {
            return nome;
        }
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        this.setLocationRelativeTo(null);

        btnDashboard.addActionListener(e -> irParaTela(Tela.DASHBOARD));
        btnProjetos.addActionListener(e -> irParaTela(Tela.PROJETOS));

        pnlBarraLateral.add(new PnlLinkBarraLateral());

        irParaTela(Tela.DASHBOARD);
    }

    private void irParaTela(Tela tela) {
        // 1. Removemos tudo o que está no container agora para liberar memória
        pnlConteudo.removeAll();

        // 2. Criamos uma instância "zerada"
        JPanel novaTela = tela.getPanel();

        // 3. Adicionamos e mostramos
        pnlConteudo.add(novaTela, tela.getNome());
        pnlConteudo.revalidate();
        pnlConteudo.repaint();

        CardLayout card = (CardLayout) pnlConteudo.getLayout();
        card.show(pnlConteudo, tela.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnProjetos = new javax.swing.JButton();
        btnEquipe = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        pnlConteudo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITERUM");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlBarraLateral.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));
        pnlBarraLateral.setMinimumSize(new java.awt.Dimension(200, 0));
        pnlBarraLateral.setPreferredSize(new java.awt.Dimension(200, 0));
        pnlBarraLateral.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITERUM");
        pnlBarraLateral.add(jLabel1);

        btnDashboard.setText("DASHBOARD");
        pnlBarraLateral.add(btnDashboard);

        btnProjetos.setText("PROJETOS");
        btnProjetos.addActionListener(this::btnProjetosActionPerformed);
        pnlBarraLateral.add(btnProjetos);

        btnEquipe.setText("EQUIPE");
        pnlBarraLateral.add(btnEquipe);

        btnRelatorios.setText("RELATÓRIOS´");
        pnlBarraLateral.add(btnRelatorios);

        getContentPane().add(pnlBarraLateral, java.awt.BorderLayout.LINE_START);

        pnlConteudo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConteudo.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjetosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnProjetosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnProjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // 1. Registra o pacote "iterum" como fonte de customizações
            com.formdev.flatlaf.FlatLaf.registerCustomDefaultsSource("iterum");

            // 2. Inicializa o tema Light (ele buscará o arquivo FlatLightLaf.properties)
            com.formdev.flatlaf.FlatLightLaf.setup();

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, "Erro ao carregar o tema IFES", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEquipe;
    private javax.swing.JButton btnProjetos;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBarraLateral;
    private javax.swing.JPanel pnlConteudo;
    // End of variables declaration//GEN-END:variables
}
