/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iterum.view;

import iterum.view.componentes.PnlCardProjeto;

/**
 *
 * @author evandro
 */
public class PnlProjetos extends javax.swing.JPanel {

    /**
     * Creates new form pnlProjetos
     */
    public PnlProjetos() {
        initComponents();
        
        atualizarListagem();
    }

    public void atualizarListagem() {
        pnlListaProjetos.removeAll();
        
        for (int i = 0; i < 7; i++) {
            pnlListaProjetos.add(new PnlCardProjeto());
        }

        pnlListaProjetos.revalidate();
        pnlListaProjetos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlListaProjetos = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PROJETOS");
        add(lblTitulo, java.awt.BorderLayout.NORTH);

        pnlListaProjetos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        add(pnlListaProjetos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlListaProjetos;
    // End of variables declaration//GEN-END:variables
}
